#!/usr/bin/env bash
#A script that displays To infinity and beyond indefinitely,
#with a sleep 2 in between each iteration and "I am inviscible!!!"
#when receiving a SIGTERM signal.


while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done