#!/usr/bin/env bash
#A script that displays numbers from 1 to 100.


cnt=1

while [ "$cnt" -le 100 ]; do
	if ((cnt % 3 == 0)) && ((cnt % 5 == 0)); then
        	echo "FizzBuzz"
    	elif ((cnt % 3 == 0)); then
        	echo "Fizz"
    	elif ((cnt % 5 == 0)); then
        	echo "Buzz"
    	else
        	echo "$cnt"
    	fi
    		((cnt++))
done