#!/usr/bin/env bash
#A script that loops from 1 to 10, displaying "bad luck"
#for the 4th loop iteration; "good luck" for the 8th loop
#iteration; "Best School" for the other iterations


x=1
while [ "$x" -le 10 ]; do
        if [ "$x" -eq 4 ]; then
                echo "bad luck"
        elif [ "$x" -eq 8 ]; then
                echo "good luck"
        else
                echo "Best School"
        fi
        ((x++))
done