#!/usr/bin/env bash
#A script that displays the time for 12 hours and 59 minutes:
#displaying hours from 0 to 12
#displaying minutes from 1 to 59


hrs=0
while [ "$hrs" -le 12 ]; do
	echo "Hour: $hrs"
	min=1
	while [ "$min" -le 59 ]; do
		echo "$min"
		((min++))
	done
	((hrs++))
done
